# Generated by Django 4.0.3 on 2022-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0009_car_dealership_is_published_and_more'),
        ('suplier', '0003_founder_is_published_founder_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplier',
            name='car',
            field=models.ManyToManyField(to='car_dealership.cars'),
        ),
    ]
