# Generated by Django 4.0.3 on 2022-03-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suplier', '0004_suplier_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='pl_of_b',
            field=models.CharField(help_text='Страна, город', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='second_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suplier',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suplier.founder'),
        ),
    ]
