# Generated by Django 4.0.3 on 2022-04-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaser',
            options={'ordering': ['first_name'], 'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaser.purchaser')),
            ],
        ),
    ]
