# Generated by Django 4.0.3 on 2022-04-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0002_alter_purchaser_options_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['value'], 'verbose_name': 'Баланс'},
        ),
    ]
