# Generated by Django 4.0.3 on 2022-04-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0003_alter_balance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='balance',
            new_name='purchaser',
        ),
    ]
