version: '3.3'
services:

  postgres:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:latest

  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./autoshop/:/app/
    depends_on:
      - redis
      - postgres
    links:
      - postgres
      - redis
    environment:
      - DJANGO_DEBUG=False
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    command: |
      python manage.py runserver 0.0.0.0:8000
