# Generated by Django 4.0.3 on 2022-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
