# Generated by Django 4.0.3 on 2022-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0002_cars_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_foundation', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('number_of_purchasers', models.IntegerField()),
                ('about_company', models.TextField(blank=True)),
                ('email_of_company', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='supliers',
            field=models.ManyToManyField(to='car_dealership.suplier'),
        ),
    ]
