# Generated by Django 4.0.3 on 2022-03-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0003_suplier_cars_supliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplier',
            name='about_company',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='email_of_company',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='location',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='number_of_purchasers',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='year_of_foundation',
        ),
    ]
