# Generated by Django 4.0.3 on 2022-03-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0004_remove_suplier_about_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='curenncy',
            field=models.CharField(choices=[('E', 'Euro'), ('D', 'Dollar'), ('R', 'Rub')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=12000),
        ),
    ]
