# Generated by Django 4.0.3 on 2022-03-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0005_cars_curenncy_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='curenncy',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('RUB', 'Rubles')], default='USD', max_length=3),
        ),
    ]
