# Generated by Django 4.0.3 on 2022-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0007_raiting_rewiew_remove_cars_supliers_delete_suplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(help_text='Введите страну, город', max_length=255)),
                ('contact', models.EmailField(max_length=254)),
                ('car', models.ManyToManyField(to='car_dealership.cars')),
            ],
        ),
    ]
