# Generated by Django 4.0.3 on 2022-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0008_car_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_dealership',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car_dealership',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='car_dealership',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
