# Generated by Django 4.0.3 on 2022-03-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0009_car_dealership_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_dealership',
            name='characteristic',
            field=models.TextField(blank=True),
        ),
    ]
