# Generated by Django 4.0.3 on 2022-04-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
