# Generated by Django 4.0.3 on 2022-04-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('car_dealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_dealership',
            name='supplier',
            field=models.ManyToManyField(null=True, related_name='supplier_cardealer', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='car',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='car_dealership.category'),
        ),
    ]
