# Generated by Django 4.0.3 on 2022-04-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0001_initial'),
        ('car_dealership', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiew',
            new_name='Review',
        ),
    ]
