# Generated by Django 4.0.3 on 2022-04-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0002_rename_rewiew_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raiting',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
    ]
