# Generated by Django 4.0.3 on 2022-04-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0003_alter_raiting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_dealershipSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('RUB', 'RUB')], default='USD', max_length=3)),
                ('sale', models.CharField(choices=[('20%', 'Last Chanсe'), ('-', 'No Sale'), ('5%', 'Seasonal Discount')], default='-', max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.car')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.car_dealership')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
