# Generated by Django 4.0.3 on 2022-04-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0003_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
