# Generated by Django 4.0.3 on 2022-04-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0003_remove_car_dealership_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_m2m_Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='car_dealership',
            name='car',
        ),
        migrations.AddField(
            model_name='car_dealership',
            name='adress',
            field=models.CharField(help_text='Улица с номером дома', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car_dealership',
            name='cars',
            field=models.ManyToManyField(default=' ', related_name='car_dealership', through='car_dealership.Car_m2m_Dealer', to='car_dealership.car'),
        ),
        migrations.AddField(
            model_name='car_dealership',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car_m2m_dealer',
            name='autoshop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='car_dealership.car_dealership'),
        ),
        migrations.AddField(
            model_name='car_m2m_dealer',
            name='car',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='car_dealership.car'),
        ),
    ]
