# Generated by Django 4.0.3 on 2022-04-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0004_car_dealershipselling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_dealershipselling',
            options={'verbose_name': 'Продажа авто'},
        ),
    ]
