# Generated by Django 4.0.3 on 2022-04-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0004_car_m2m_dealer_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_m2m_dealer',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='car_dealership',
            name='cars',
            field=models.ManyToManyField(through='car_dealership.Car_m2m_Dealer', to='car_dealership.car'),
        ),
    ]
