# Generated by Django 4.0.3 on 2022-04-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0005_car_m2m_dealer_date_joined_alter_car_dealership_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiting',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='time_update',
        ),
        migrations.RemoveField(
            model_name='rewiew',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='rewiew',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='rewiew',
            name='time_update',
        ),
        migrations.AlterField(
            model_name='raiting',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carraiting', to='car_dealership.car'),
        ),
    ]
