# Generated by Django 4.0.3 on 2022-04-13 08:14

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0005_alter_car_dealershipselling_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_dealershipSeasonsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('name_of_sale', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('RUB', 'RUB')], default='USD', max_length=3)),
                ('sale', models.CharField(choices=[('20%', 'Last Chanсe'), ('-', 'No Sale'), ('5%', 'Seasonal Discount')], default='-', max_length=255)),
                ('location_of_dealership', django_countries.fields.CountryField(max_length=2)),
                ('end_time', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.car')),
                ('car_dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.car_dealership')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
