# Generated by Django 4.0.3 on 2022-04-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0006_car_dealershipseasonsales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_dealershipseasonsales',
            options={'verbose_name': 'Сезонная скидка', 'verbose_name_plural': 'Сезонные скидки'},
        ),
    ]
