# Generated by Django 4.0.3 on 2022-04-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('car_dealership', '0007_raiting_is_published_raiting_time_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='value',
        ),
        migrations.AddField(
            model_name='raiting',
            name='raiting_ptr',
            field=models.OneToOneField(auto_created=True, default=3, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.raiting'),
            preserve_default=False,
        ),
    ]
