# Generated by Django 4.0.3 on 2022-04-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0008_remove_raiting_id_remove_raiting_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_dealership',
            options={'verbose_name': 'Aвтосалон', 'verbose_name_plural': 'Aвтосалоны'},
        ),
    ]
