# Generated by Django 4.0.3 on 2022-04-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0008_rename_price_car_dealershipseasonsales_first_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_m2m_dealer',
            options={'verbose_name': 'Список автомобилей автосалона'},
        ),
    ]
