# Generated by Django 4.0.3 on 2022-04-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0009_alter_car_dealership_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['title'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='raiting',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='rewiew',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
