# Generated by Django 4.0.3 on 2022-04-07 13:38

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_dealership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('second_name', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('place_of_birth', django_countries.fields.CountryField(max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('year_of_foundation', models.IntegerField(validators=[core.validators.check_year_of_foundation])),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('number_of_purchasers', models.IntegerField()),
                ('about_company', models.TextField(blank=True)),
                ('email_of_company', models.EmailField(max_length=254)),
                ('autoshops', models.ManyToManyField(related_name='cardealer_supplier', to='car_dealership.car_dealership')),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.founder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('value', models.IntegerField(default=9, validators=[core.validators.check_raiting])),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
