# Generated by Django 4.0.3 on 2022-04-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='autoshops',
            field=models.ManyToManyField(related_name='cardealer_supplier', to='car_dealership.car_dealership'),
        ),
    ]
