# Generated by Django 4.0.3 on 2022-04-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='time_update',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='time_update',
        ),
    ]
