# Generated by Django 4.0.3 on 2022-03-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaser',
            name='age',
            field=models.IntegerField(),
        ),
    ]
