# Generated by Django 4.0.3 on 2022-04-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
