# Generated by Django 4.0.3 on 2022-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0002_alter_purchaser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaser',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
