# Generated by Django 4.0.3 on 2022-04-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0002_remove_review_purchaser'),
        ('purchaser', '0002_delete_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchaser',
        ),
    ]
