# Generated by Django 4.0.3 on 2022-04-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('purchaser', models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='purchaser.purchaser')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
                'ordering': ['value'],
            },
        ),
    ]
